### ISSUE TITLE
Houdini 17.5

### ISSUE THREAD

**Issue by MirHadi-jam** [dchow1992/nemarkingmenu#14]
Hello

At startup it comes up with lots of error in the console like:

**Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromlines?PythonModule", line 7, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraphvellumutils.py", line 2, in <module>
    import nodegraph
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraph.py", line 21, in <module>
    import nodegraphhooks as hooks
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\nodegraphhooks.py", line 9, in <module>
    from houdini_markingmenu import markingmenu as mm
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\markingmenu.py", line 13, in <module>
    import utils
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\utils.py", line 101, in <module>
    def getContext(editor=hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)):
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 57159, in paneTabOfType
    return _hou.ui_paneTabOfType(*args)

NotAvailable: Not available in this context.
The UI is not created yet

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromlines?OnInstall", line 3, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 35022, in __getattr__
    def __getattr__(*args): return _hou.HDAModule___getattr__(*args)
AttributeError: 'module' object has no attribute 'create_node_template'

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromcurves?PythonModule", line 7, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraphvellumutils.py", line 2, in <module>
    import nodegraph
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraph.py", line 21, in <module>
    import nodegraphhooks as hooks
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\nodegraphhooks.py", line 9, in <module>
    from houdini_markingmenu import markingmenu as mm
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\markingmenu.py", line 13, in <module>
    import utils
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\utils.py", line 101, in <module>
    def getContext(editor=hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)):
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 57159, in paneTabOfType
    return _hou.ui_paneTabOfType(*args)
NotAvailable: Not available in this context.
The UI is not created yet

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromcurves?OnInstall", line 3, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 35022, in __getattr__
    def __getattr__(*args): return _hou.HDAModule___getattr__(*args)
AttributeError: 'module' object has no attribute 'create_node_template'

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromrules?PythonModule", line 7, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraphvellumutils.py", line 2, in <module>
    import nodegraph
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraph.py", line 21, in <module>
    import nodegraphhooks as hooks
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\nodegraphhooks.py", line 9, in <module>
    from houdini_markingmenu import markingmenu as mm
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\markingmenu.py", line 13, in <module>
    import utils
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\utils.py", line 101, in <module>
    def getContext(editor=hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)):
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 57159, in paneTabOfType
    return _hou.ui_paneTabOfType(*args)

NotAvailable: Not available in this context.
The UI is not created yet

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdconstraintsfromrules?OnInstall", line 3, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 35022, in __getattr__
    def __getattr__(*args): return _hou.HDAModule___getattr__(*args)
AttributeError: 'module' object has no attribute 'create_node_template'

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdpaint?PythonModule", line 9, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraphvellumutils.py", line 2, in <module>
    import nodegraph
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\nodegraph.py", line 21, in <module>
    import nodegraphhooks as hooks
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\nodegraphhooks.py", line 9, in <module>
    from houdini_markingmenu import markingmenu as mm
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\markingmenu.py", line 13, in <module>
    import utils
  File "C:/Users/jamshidi/Documents/houdini17.5/python2.7libs\houdini_markingmenu\utils.py", line 101, in <module>
    def getContext(editor=hou.ui.paneTabOfType(hou.paneTabType.NetworkEditor)):
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 57159, in paneTabOfType
    return _hou.ui_paneTabOfType(*args)
NotAvailable: Not available in this context.
The UI is not created yet

Error running event handler:
Traceback (most recent call last):
  File "opdef:/Sop/rbdpaint?OnInstall", line 3, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.398/houdini/python2.7libs\hou.py", line 35022, in __getattr__
    def __getattr__(*args): return _hou.HDAModule___getattr__(*args)
AttributeError: 'module' object has no attribute 'createViewerStateTemplate'**

**Comment by dchow1992** [comment]
fixed
